server:
  port: 8088
  servlet:
    context-path: /demo

#spring:
#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: NEVER
#    auto-startup: true
#    properties:
#      org:
#        quartz:
#          scheduler:
#            instanceName: MyScheduler
#            instanceId: AUTO
#          jobStore:
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            isClustered: true
#            misfireThreshold: 60000
#            clusterCheckinInterval: 10000
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 10
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
